#include <stdlib.h>
#include <stdio.h> 
#include <string.h>
#include <mpi.h>

#include "read_write_pgm_image.h"


void write_pgm_image_header(unsigned int maxval, unsigned int xsize, unsigned int ysize, MPI_Offset* current_position,  const char *image_name) {
 /*
  * image        : a pointer to the memory region that contains the image
  * maxval       : either 255 or 65536
  * xsize, ysize : x and y dimensions of the image
  * image_name   : the name of the file to be written
  */
  FILE* image_file;
  image_file = fopen(image_name, "wb");
  //Writing header
  
  fprintf(image_file, "P5\n# generated by\n# Cecilia Zagni\n%d %d\n%d\n", xsize, ysize, maxval);
  *current_position=  ftell(image_file);
  fclose(image_file);
  
  //printf("Offset %lld \n",*current_position);

  return ;
}


void write_pgm_image_body( void *image, unsigned int maxval, unsigned int buffer_size, MPI_Offset* current_position, const char *image_name) {
	 /*
	  *   * image        : a pointer to the memory region that contains the image
	  *     * maxval       : either 255 or 65536
	  *       * xsize, ysize : x and y dimensions of the image
	  *         * image_name   : the name of the file to be written
	  *           */

	MPI_File image_file;

        // open file for writing
        MPI_File_open(MPI_COMM_WORLD, image_name, MPI_MODE_WRONLY, MPI_INFO_NULL, &image_file);
				                        
	// Calculate the total size of the data to write
	int color_depth = 1 + (maxval > 255);
	MPI_Offset total_data_size = buffer_size * color_depth;
	int myrank;
	MPI_Comm_rank(MPI_COMM_WORLD,&myrank);
	//printf("i'm %d , write at %lld len %lld \n", myrank,*current_position,total_data_size);
	// Write data starting at the current position
	MPI_File_write_at_all(image_file, *current_position, image, total_data_size, MPI_BYTE, MPI_STATUS_IGNORE);
	
	// Close the MPI-IO file
	MPI_File_close(&image_file);

	return ;
}

                                                                                              
void read_pgm_image_header(unsigned int *maxval, unsigned int *xsize, unsigned int *ysize, const char *image_name,unsigned int* offset  ) {
	/*
	 * image        : a pointer to the pointer that will contain the image
         * maxval       : a pointer to the int that will store the maximum intensity in the image
         * xsize, ysize : pointers to the x and y sizes
         * image_name   : the name of the file to be read
         */
	int rank;
	MPI_Comm_rank(MPI_COMM_WORLD,&rank);

	//printf("i'm %d , e sto per leggere l'header \n", rank);
	
	FILE* image_file; 	
	image_file = fopen(image_name, "rb"); 
	

	*xsize = *ysize = *maxval = 0;
	
	char    MagicN[2];
	char   *line = NULL;
	size_t  k, n = 0;
	
	// get the Magic Number
	k = fscanf(image_file, "%2s%*c", MagicN );
	
	// skip all the comments
	k = getline( &line, &n, image_file);
	while ( (k > 0) && (line[0]=='#') )
		k = getline( &line, &n, image_file);
	
	// file header
	if (k > 0) {
	  k = sscanf(line, "%d%*c%d%*c%d%*c", xsize, ysize, maxval);
	  if ( k < 3 )
	    fscanf(image_file, "%d%*c", maxval);
	}
	else {
	  
	  *maxval = -1;         // this is the signal that there was an I/O error                                                                                                       	                			    // while reading the image header
	  
	  free( line );
	  return;
	}
	free( line );

	//printf("I'm %d, xsize: %d ysize: %d maxval: %d\n",rank,*xsize,*ysize,*maxval);

	*offset = ftell(image_file);
	//printf("I'm %d, offset: %u \n",rank,*offset);
	fclose(image_file);
	return;
}



void read_pgm_image_body(void* grid,long int buffer_size, long int offset, const char *image_name ) {
  MPI_File image_file;

        // open file for writing
  MPI_File_open(MPI_COMM_WORLD, image_name, MPI_MODE_RDONLY , MPI_INFO_NULL, &image_file);

  //  int MPI_File_read_at_all(MPI_File fh, MPI_Offset offset,
  //void *buf, int count, MPI_Datatype datatype,
  //MPI_Status *status)
  MPI_Offset mpi_offset=offset;
  
  MPI_File_read_at_all(image_file,mpi_offset,grid,buffer_size,MPI_CHAR,MPI_STATUS_IGNORE);
  MPI_File_close(&image_file);
  
}
