#include <stdlib.h>
#include <stdio.h> 
#include <string.h>
#include <mpi.h>

#include "read_write_pgm_image.h"

#define XWIDTH 256
#define YWIDTH 256
#define MAXVAL 65535


// =============================================================
// //  utilities for managinf pgm files
// //
// //  * write_pgm_image
// //  * read_pgm_image
// //
// // =============================================================

void write_pgm_image( void *image, unsigned int maxval, unsigned int xsize, unsigned int ysize, const char *image_name) {
	 /*
	  *   * image        : a pointer to the memory region that contains the image
	  *     * maxval       : either 255 or 65536
	  *       * xsize, ysize : x and y dimensions of the image
	  *         * image_name   : the name of the file to be written
	  *           */

	        FILE* image_file;
		        image_file = fopen(image_name, "w");

			         //Writing header
			         int color_depth = 1 + ( maxval > 255 );
				                 fprintf(image_file, "P5\n# generated by\n# Cecilia Zagni\n%d %d\n%d\n", xsize, ysize, maxval);
				
				                         // Writing file
				                                 fwrite( image, 1, xsize*ysize*color_depth, image_file);
				                                         fclose(image_file);
				                                                 return ;
				                                                 }






void write_pgm_image_header(unsigned int maxval, unsigned int xsize, unsigned int ysize, MPI_Offset* current_position,  const char *image_name) {
 /*
  * image        : a pointer to the memory region that contains the image
  * maxval       : either 255 or 65536
  * xsize, ysize : x and y dimensions of the image
  * image_name   : the name of the file to be written
  */

	MPI_File* image_file = NULL;

	// open file for writing
	MPI_File_open(MPI_COMM_WORLD, image_name, MPI_MODE_WRONLY | MPI_MODE_CREATE, MPI_INFO_NULL, image_file);
	

	// Write data to the file using MPI_File_write
	char header[100];
	snprintf(header, sizeof(header), "P5\n# generated by\n# Cecilia Zagni\n%d %d\n%d\n", xsize, ysize, maxval);
	MPI_File_write(*image_file, header, strlen(header), MPI_CHAR, MPI_STATUS_IGNORE);

	// Save the current position using MPI_File_get_position
	MPI_File_get_position(*image_file, current_position);
	
	// Close the file
	MPI_File_close(image_file);	

	return ;
}


void write_pgm_image_body( void *image, unsigned int maxval, unsigned int buffer_size, MPI_Offset* current_position, const char *image_name) {
	 /*
	  *   * image        : a pointer to the memory region that contains the image
	  *     * maxval       : either 255 or 65536
	  *       * xsize, ysize : x and y dimensions of the image
	  *         * image_name   : the name of the file to be written
	  *           */

	MPI_File* image_file = NULL;

        // open file for writing
        MPI_File_open(MPI_COMM_WORLD, image_name, MPI_MODE_WRONLY | MPI_MODE_CREATE, MPI_INFO_NULL, image_file);
				                        
	// Calculate the total size of the data to write
	int color_depth = 1 + (maxval > 255);
	MPI_Offset total_data_size = buffer_size * color_depth;

	// Write data starting at the current position
	MPI_File_write_at(*image_file, *current_position, image, total_data_size, MPI_BYTE, MPI_STATUS_IGNORE);
	
	// Close the MPI-IO file
	MPI_File_close(image_file);

	return ;
}

                                                                                              
void read_pgm_image( void **image, unsigned int *maxval, unsigned int *xsize, unsigned int *ysize, const char *image_name) {
	/*
	 * image        : a pointer to the pointer that will contain the image
         * maxval       : a pointer to the int that will store the maximum intensity in the image
         * xsize, ysize : pointers to the x and y sizes
         * image_name   : the name of the file to be read
         */
	
	FILE* image_file; 	
	image_file = fopen(image_name, "r"); 
	
	*image = NULL;
	*xsize = *ysize = *maxval = 0;
	
	char    MagicN[2];
	char   *line = NULL;
	size_t  k, n = 0;
	
	// get the Magic Number
	k = fscanf(image_file, "%2s%*c", MagicN );
	
	// skip all the comments
	k = getline( &line, &n, image_file);
	while ( (k > 0) && (line[0]=='#') )
		k = getline( &line, &n, image_file);
	
	// file header
	if (k > 0) {
		k = sscanf(line, "%d%*c%d%*c%d%*c", xsize, ysize, maxval);
		if ( k < 3 )
			fscanf(image_file, "%d%*c", maxval);
	}
	else {
		*maxval = -1;         // this is the signal that there was an I/O error                                                                                                       	                			    // while reading the image header
                                                                                       
		free( line );
		return;
	}
	free( line );
	
	int color_depth = 1 + ( *maxval > 255 );
	unsigned int size = *xsize * *ysize * color_depth;
	if ( (*image = (char*)malloc( size )) == NULL ){
		fclose(image_file);
		*maxval = -2;         // this is the signal that memory was insufficient				      
		*xsize  = 0;
		*ysize  = 0;
		return;
	}

	if ( fread( *image, 1, size, image_file) != size ) {
		free( image );
		image   = NULL;
		*maxval = -3;         // this is the signal that there was an i/o error				      
		*xsize  = 0;                                                           
		*ysize  = 0;
	}  
	
	fclose(image_file);
	return;
}
